# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-08 20:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='event_time',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='date of the event that caused the snowfall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='haul_stack_estimate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='cost estimate for future snow hauling or stacking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='haul_stack_status',
            field=models.IntegerField(choices=[(0, b'NONE'), (1, b'NEEDS_STACKING'), (2, b'NEEDS_HAULING')], default=0, verbose_name='any need for snow hauling or stacking?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='last_service_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='time of last service at this location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='safety_concerns',
            field=models.TextField(default='', max_length=1000, verbose_name='any concerns? let us know of all site conditions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='snow_instructions',
            field=models.TextField(default='', max_length=1000, verbose_name='extra instructions for handling remaining snow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='building_type',
            field=models.IntegerField(choices=[(1, b'STANDALONE'), (2, b'MIXED_USE')], default=1, verbose_name='type of the property to service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.IntegerField(choices=[(-1, b'REJECTED'), (1, b'CREATED'), (2, b'INITIALIZED'), (3, b'SAFETY_REVIEWED'), (4, b'SAFETY_REVIEW_CLOSED'), (5, b'PRELIM_GENERATED'), (6, b'PRE_FORECAST_REVIEWED'), (7, b'FORECASTED'), (8, b'SENT_TO_PROVIDER'), (9, b'VALIDATED'), (10, b'FINALIZED')]),
        ),
    ]
