# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='building',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='invoices.Building'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='storm_name',
            field=models.TextField(default='', max_length=100, verbose_name='name of the storm'),
            preserve_default=False,
        ),
    ]
