# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20180508_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceProxyDiscrepancy',
            fields=[
            ],
            options={
                'verbose_name': 'internal regional admin',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.regionaladmin',),
        ),
        migrations.CreateModel(
            name='InvoiceProxyForecast',
            fields=[
            ],
            options={
                'verbose_name': '',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.invoice',),
        ),
        migrations.CreateModel(
            name='InvoiceProxyVendor',
            fields=[
            ],
            options={
                'verbose_name': 'Prelim Invoices',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.invoice',),
        ),
        migrations.AddField(
            model_name='workorder',
            name='num_plows',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='num_salts',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
