# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 05:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0002_auto_20180409_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='system_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
