# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20180508_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceproxydiscrepancy',
            options={'verbose_name': 'Discrepancy Reports'},
        ),
        migrations.AlterModelOptions(
            name='invoiceproxyforecast',
            options={'verbose_name': 'Forecast Report'},
        ),
        migrations.AlterModelOptions(
            name='invoiceproxyvendor',
            options={'verbose_name': 'Closeout Report'},
        ),
        migrations.AlterField(
            model_name='safetyreport',
            name='safety_concerns',
            field=models.CharField(blank=True, max_length=255, verbose_name='Any concerns? Let us know of all site conditions'),
        ),
        migrations.AlterField(
            model_name='safetyreport',
            name='snow_instructions',
            field=models.CharField(blank=True, max_length=255, verbose_name='Extra instructions for handling remaining snow'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='num_plows',
            field=models.IntegerField(verbose_name='# Plows'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='num_salts',
            field=models.IntegerField(verbose_name='# Salts'),
        ),
    ]
