# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-10 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20180510_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_locations', to='invoices.Building'),
        ),
    ]
