# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_auto_20180510_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProxyServiceDiscrepancy',
            fields=[
            ],
            options={
                'verbose_name': 'Discrepancy Report',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.workorder',),
        ),
        migrations.CreateModel(
            name='WorkProxyServiceForecast',
            fields=[
            ],
            options={
                'verbose_name': 'Service Forecast',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.workorder',),
        ),
        migrations.AddField(
            model_name='workorder',
            name='failed_service',
            field=models.BooleanField(default=False, verbose_name='Service Failed?'),
        ),
    ]
