# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_auto_20180514_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='vendor',
            new_name='service_provider',
        ),
    ]
