# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_workorder_work_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='vendor',
            new_name='service_provider',
        ),
    ]
