# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_auto_20180514_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='storm_date',
            field=models.DateField(blank=True, help_text='Date of the last storm event', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='storm_name',
            field=models.CharField(blank=True, help_text='Name of the event for which work is being done in response', max_length=100, null=True),
        ),
    ]
