# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_auto_20180514_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='num_plows',
            field=models.IntegerField(blank=True, null=True, verbose_name='# Plows'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='num_salts',
            field=models.IntegerField(blank=True, null=True, verbose_name='# Salts'),
        ),
    ]
