# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_auto_20180514_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyreport',
            name='last_service_date',
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='service_time',
            field=models.DateField(blank=True, null=True, verbose_name='Service Time'),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='site_serviced',
            field=models.BooleanField(default=True, verbose_name='Site Serviced?'),
        ),
        migrations.AlterField(
            model_name='building',
            name='deice_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cost per de-icing w/o tax'),
        ),
        migrations.AlterField(
            model_name='building',
            name='deice_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tax per de-icing'),
        ),
        migrations.AlterField(
            model_name='building',
            name='plow_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cost per plow w/o tax'),
        ),
        migrations.AlterField(
            model_name='building',
            name='plow_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tax per plow'),
        ),
        migrations.AlterField(
            model_name='safetyreport',
            name='safe_to_open',
            field=models.BooleanField(default=True, verbose_name='Safe to open site?'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='last_service_date',
            field=models.DateField(blank=True, help_text='Date of last service at this location', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='num_plows',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='# Plows'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='num_salts',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='# Salts'),
        ),
    ]
