# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_auto_20180515_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='storm_date',
        ),
        migrations.AddField(
            model_name='workorder',
            name='service_time',
            field=models.DateTimeField(blank=True, help_text='Last time serviced', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='last_service_date',
            field=models.DateField(blank=True, help_text='Date of the last service', null=True),
        ),
    ]
