# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_auto_20180516_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='service_time',
            field=models.CharField(blank=True, choices=[('Midnight - 4 AM', 'Midnight - 4 AM'), ('4 AM - 8 AM', '4 AM - 8 AM'), ('8AM - Noon', '8 AM - Noon'), ('Noon - 4 PM', 'Noon - 4 PM'), ('4 PM - 8 PM', '4 PM - 8 PM'), ('8 PM - Midnight', '8 PM - Midnight')], help_text='Last time serviced', max_length=255, null=True),
        ),
    ]
