# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_auto_20180516_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBREInvoiceProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Preliminary Invoice',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.invoice',),
        ),
        migrations.CreateModel(
            name='CBRESafetyProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Safety Report',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.invoice',),
        ),
        migrations.CreateModel(
            name='NWABuilding',
            fields=[
            ],
            options={
                'verbose_name': 'Building',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.building',),
        ),
        migrations.CreateModel(
            name='NWAInvoiceProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Preliminary Invoice',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.invoice',),
        ),
        migrations.CreateModel(
            name='NWASafetyProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Safety Report',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.invoice',),
        ),
        migrations.CreateModel(
            name='NWAServiceDiscrepancy',
            fields=[
            ],
            options={
                'verbose_name': 'Discrepancy Report',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.workorder',),
        ),
        migrations.CreateModel(
            name='NWAServiceForecast',
            fields=[
            ],
            options={
                'verbose_name': 'Initial Spend Forecast',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.workorder',),
        ),
        migrations.CreateModel(
            name='NWAServiceProvider',
            fields=[
            ],
            options={
                'verbose_name': 'Service Provider',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.vendor',),
        ),
        migrations.CreateModel(
            name='VendorInvoiceProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Preliminary Invoice',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.invoice',),
        ),
        migrations.CreateModel(
            name='VendorSafetyProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Safety Report',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.invoice',),
        ),
        migrations.AlterModelOptions(
            name='invoiceproxyprelim',
            options={'verbose_name': 'Preliminary Invoice'},
        ),
        migrations.AlterModelOptions(
            name='invoiceproxyvendor',
            options={'verbose_name': 'Safety Report'},
        ),
        migrations.AlterModelOptions(
            name='workproxyserviceforecast',
            options={'verbose_name': 'Initial Spend Forecast'},
        ),
        migrations.RemoveField(
            model_name='workvisit',
            name='provided_deicing',
        ),
        migrations.RemoveField(
            model_name='workvisit',
            name='provided_plowing',
        ),
        migrations.RemoveField(
            model_name='workvisit',
            name='response_time_end',
        ),
        migrations.RemoveField(
            model_name='workvisit',
            name='response_time_start',
        ),
        migrations.AddField(
            model_name='workvisit',
            name='failed_service',
            field=models.BooleanField(default=False, verbose_name='Service Failed?'),
        ),
        migrations.AddField(
            model_name='workvisit',
            name='num_plows',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='# Plows'),
        ),
        migrations.AddField(
            model_name='workvisit',
            name='num_salts',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='# Salts'),
        ),
        migrations.AddField(
            model_name='workvisit',
            name='service_time',
            field=models.CharField(blank=True, choices=[('Midnight - 4 AM', 'Midnight - 4 AM'), ('4 AM - 8 AM', '4 AM - 8 AM'), ('8AM - Noon', '8 AM - Noon'), ('Noon - 4 PM', 'Noon - 4 PM'), ('4 PM - 8 PM', '4 PM - 8 PM'), ('8 PM - Midnight', '8 PM - Midnight')], help_text='Last time serviced', max_length=255, null=True),
        ),
    ]
