# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_auto_20180522_1355'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='workvisit',
            managers=[
                ('aggregates', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('not_created', 'Not Created'), ('preliminary_created', 'Preliminary'), ('submitted', 'Submitted'), ('reviewed - 4 PM', 'Reviewed'), ('dispute', 'In Dispute'), ('finalized', 'Finalized')], default='not_created', max_length=255),
        ),
        migrations.AlterField(
            model_name='workvisit',
            name='num_plows',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1)], default=0, null=True, verbose_name='# Plows'),
        ),
        migrations.AlterField(
            model_name='workvisit',
            name='num_salts',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1)], default=0, null=True, verbose_name='# Salts'),
        ),
    ]
