# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-24 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_auto_20180522_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('site_serviced', models.BooleanField(default=True, verbose_name='Site Serviced?')),
                ('safe_to_open', models.BooleanField(default=True, verbose_name='Safe to open site?')),
                ('safety_concerns', models.CharField(blank=True, max_length=255, verbose_name='Any concerns? Let us know of all site conditions')),
                ('snow_instructions', models.CharField(blank=True, max_length=255, verbose_name='Extra instructions for handling remaining snow')),
                ('haul_stack_status', models.IntegerField(blank=True, choices=[(0, 'NONE'), (1, 'NEEDS_STACKING'), (2, 'NEEDS_HAULING')], default=0, null=True, verbose_name='Snow hauling or stacking required?')),
                ('haul_stack_estimate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Cost estimate for future snow hauling or stacking')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cbreinvoiceproxy',
            options={'verbose_name': 'Submitted Invoice'},
        ),
        migrations.RemoveField(
            model_name='safetyreport',
            name='service_time',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('not_created', 'Safety Report - Initial'), ('safety_report', 'Safety Report - Created'), ('preliminary_created', 'Preliminary Invoice Created'), ('submitted', 'Invoice Submitted'), ('reviewed - 4 PM', 'Reviewed'), ('dispute', 'In Dispute'), ('finalized', 'Finalized')], default='not_created', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='safetyvisit',
            name='safety_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.SafetyReport'),
        ),
    ]
