# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-24 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0023_auto_20180524_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyvisit',
            name='inspection_date',
            field=models.DateField(blank=True, help_text='Date of the safety check', null=True),
        ),
        migrations.AddField(
            model_name='workvisit',
            name='service_date',
            field=models.DateField(blank=True, help_text='Date the service was performed', null=True),
        ),
    ]
