# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-24 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0024_auto_20180524_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('not_created', 'Safety Report - Initial'), ('safety_report', 'Safety Report - Created'), ('preliminary_created', 'Preliminary Invoice'), ('submitted', 'Invoice Submitted'), ('reviewed - 4 PM', 'Reviewed'), ('dispute', 'In Dispute'), ('finalized', 'Finalized')], default='not_created', max_length=255, null=True),
        ),
    ]
