# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-24 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0025_auto_20180524_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('work_order_code', models.CharField(max_length=255)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('not_created', 'Safety Report - Initial'), ('safety_report', 'Closeout Report Generated'), ('preliminary_created', 'Preliminary Invoice - In Progress'), ('submitted', 'Invoice Submitted'), ('reviewed - 4 PM', 'Reviewed'), ('dispute', 'In Dispute'), ('finalized', 'Finalized')], default='not_created', max_length=255, null=True),
        ),
    ]
