# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-24 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0027_auto_20180524_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStationSuperProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Weather Station',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.weatherstation',),
        ),
        migrations.AddField(
            model_name='workorderid',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
