# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-31 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0028_auto_20180524_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='NWASubmittedInvoiceProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Submitted Invoice',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.invoice',),
        ),
        migrations.CreateModel(
            name='WorkOrderIDSuperProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Available Work Order ID',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.workorderid',),
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='num_plows',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='num_salts',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('not_created', 'Safety Report - Initial'), ('safety_report', 'Closeout Report Generated'), ('preliminary_created', 'Preliminary Invoice - In Progress'), ('submitted', 'Invoice Submitted - In Review'), ('reviewed', 'Reviewed'), ('dispute', 'In Dispute'), ('finalized', 'Finalized')], default='not_created', max_length=255, null=True),
        ),
    ]
