# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-31 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0029_auto_20180531_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='failed_service',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='service_time',
        ),
    ]
