# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-01 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0030_auto_20180531_0828'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='workvisit',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='cst_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='nws_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
