# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-01 23:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0031_auto_20180601_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='facility_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
