# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-02 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0033_auto_20180601_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceproxyforecast',
            options={'verbose_name': 'Initial Spend Forecast'},
        ),
    ]
