# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-04 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0034_auto_20180602_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyreport',
            name='haul_stack_estimate',
        ),
        migrations.RemoveField(
            model_name='safetyreport',
            name='haul_stack_status',
        ),
        migrations.RemoveField(
            model_name='safetyreport',
            name='safe_to_open',
        ),
        migrations.RemoveField(
            model_name='safetyreport',
            name='safety_concerns',
        ),
        migrations.RemoveField(
            model_name='safetyreport',
            name='site_serviced',
        ),
        migrations.RemoveField(
            model_name='safetyreport',
            name='snow_instructions',
        ),
    ]
