# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-04 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0035_auto_20180604_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyvisit',
            name='inspection_date',
            field=models.DateField(blank=True, default='2018-12-08', help_text='Date of the safety check', null=True),
        ),
    ]
