# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0036_auto_20180604_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceproxyprelim',
            options={'verbose_name': 'Invoice'},
        ),
        migrations.AlterModelOptions(
            name='nwainvoiceproxy',
            options={'verbose_name': 'Invoice'},
        ),
        migrations.AlterModelOptions(
            name='vendorinvoiceproxy',
            options={'verbose_name': 'Invoice'},
        ),
        migrations.AddField(
            model_name='building',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='safetyvisit',
            name='inspection_date',
            field=models.DateField(blank=True, default='2017-12-08', help_text='Date of the safety check', null=True),
        ),
    ]
