# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-13 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0037_auto_20180607_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedInvoice',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices.Invoice')),
            ],
            options={
                'abstract': False,
            },
            bases=('invoices.invoice',),
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('inspection_date', models.DateField(blank=True, default='2017-12-08', help_text='Date of the safety check', null=True)),
                ('safe_to_open', models.BooleanField(default=True, verbose_name='Safe to open site?')),
                ('safety_concerns', models.CharField(blank=True, max_length=255, null=True, verbose_name='Concerns/Extra Instructions')),
                ('haul_stack_status', models.IntegerField(blank=True, choices=[(0, 'NONE'), (1, 'NEEDS_STACKING'), (2, 'NEEDS_HAULING')], default=0, null=True, verbose_name='Snow hauling or stacking required?')),
                ('haul_stack_estimate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Cost estimate for future snow hauling or stacking')),
                ('work_order_code', models.CharField(blank=True, max_length=255, null=True)),
                ('work_visit_date', models.DateField(blank=True, default='2017-12-08', help_text='Date the work was performed', null=True)),
                ('service_time', models.CharField(blank=True, choices=[('Midnight - 4 AM', 'Midnight - 4 AM'), ('4 AM - 8 AM', '4 AM - 8 AM'), ('8AM - Noon', '8 AM - Noon'), ('Noon - 4 PM', 'Noon - 4 PM'), ('4 PM - 8 PM', '4 PM - 8 PM'), ('8 PM - Midnight', '8 PM - Midnight')], help_text='Last time serviced', max_length=255, null=True)),
                ('num_plows', models.IntegerField(blank=True, choices=[(0, 0), (1, 1)], default=0, null=True, verbose_name='# Plows')),
                ('num_salts', models.IntegerField(blank=True, choices=[(0, 0), (1, 1)], default=0, null=True, verbose_name='# Salts')),
                ('failed_service', models.BooleanField(default=False, verbose_name='Service Failed?')),
                ('discrepancy_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Discrepancy Status')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Building')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice')),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
