# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-21 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0037_auto_20180607_1921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CBREInvoiceProxy',
        ),
        migrations.DeleteModel(
            name='CBRESafetyProxy',
        ),
        migrations.DeleteModel(
            name='InvoiceForecastReportProxyNWA',
        ),
        migrations.DeleteModel(
            name='InvoiceProxyDiscrepancy',
        ),
        migrations.DeleteModel(
            name='InvoiceProxyForecast',
        ),
        migrations.DeleteModel(
            name='InvoiceProxyPrelim',
        ),
        migrations.DeleteModel(
            name='InvoiceProxyVendor',
        ),
        migrations.DeleteModel(
            name='ModifiablePrelimInvoice',
        ),
        migrations.DeleteModel(
            name='NWABuilding',
        ),
        migrations.DeleteModel(
            name='NWAInvoiceProxy',
        ),
        migrations.DeleteModel(
            name='NWASafetyProxy',
        ),
        migrations.DeleteModel(
            name='NWAServiceDiscrepancy',
        ),
        migrations.DeleteModel(
            name='NWAServiceForecast',
        ),
        migrations.DeleteModel(
            name='NWAServiceProvider',
        ),
        migrations.DeleteModel(
            name='NWASubmittedInvoiceProxy',
        ),
        migrations.DeleteModel(
            name='RegionalAdminProxyNWA',
        ),
        migrations.DeleteModel(
            name='VendorInvoiceProxy',
        ),
        migrations.DeleteModel(
            name='VendorProxyCBRE',
        ),
        migrations.DeleteModel(
            name='VendorSafetyProxy',
        ),
        migrations.DeleteModel(
            name='WeatherStationSuperProxy',
        ),
        migrations.DeleteModel(
            name='WorkOrderIDSuperProxy',
        ),
        migrations.DeleteModel(
            name='WorkOrderProxyCBRE',
        ),
        migrations.DeleteModel(
            name='WorkOrderProxyNWA',
        ),
        migrations.DeleteModel(
            name='WorkOrderProxyVendor',
        ),
        migrations.DeleteModel(
            name='WorkProxyServiceDiscrepancy',
        ),
        migrations.DeleteModel(
            name='WorkProxyServiceForecast',
        ),
        migrations.CreateModel(
            name='DiscrepancyReportItemNWA',
            fields=[
            ],
            options={
                'verbose_name': 'Work Order',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.workorder',),
        ),
        migrations.CreateModel(
            name='DiscrepancyReportNWA',
            fields=[
            ],
            options={
                'verbose_name': 'Discrepancy Report',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.invoice',),
        ),
        migrations.CreateModel(
            name='InvoiceVendor',
            fields=[
            ],
            options={
                'verbose_name': 'Invoice',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.invoice',),
        ),
        migrations.CreateModel(
            name='SafetyReportVendor',
            fields=[
            ],
            options={
                'verbose_name': 'Safety Report',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.invoice',),
        ),
        migrations.CreateModel(
            name='ServiceForecastItemNWA',
            fields=[
            ],
            options={
                'verbose_name': 'Safety Report',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.safetyreport',),
        ),
        migrations.CreateModel(
            name='ServiceForecastNWA',
            fields=[
            ],
            options={
                'verbose_name': 'Service Forecast',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.invoice',),
        ),
        migrations.CreateModel(
            name='SubmittedInvoiceNWA',
            fields=[
            ],
            options={
                'verbose_name': 'Invoice',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.invoice',),
        ),
        migrations.RenameField(
            model_name='discrepancyreport',
            old_name='message',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='service_provider',
        ),
        migrations.AddField(
            model_name='invoice',
            name='dispute_status',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_discrepant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workvisit',
            name='num_salts',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2)], default=0, null=True, verbose_name='# Salts'),
        ),
    ]
