# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-26 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0038_auto_20180621_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyreport',
            name='haul_stack_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Cost estimate for future snow hauling or stacking'),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='haul_stack_status',
            field=models.IntegerField(blank=True, choices=[(0, 'NONE'), (1, 'NEEDS_STACKING'), (2, 'NEEDS_HAULING')], default=0, null=True, verbose_name='Snow hauling or stacking required?'),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='inspection_date',
            field=models.DateField(blank=True, default='2017-12-08', help_text='Date of the safety check', null=True),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='safe_to_open',
            field=models.BooleanField(default=True, verbose_name='Safe to open site?'),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='safety_concerns',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Concerns/Extra Instructions'),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='site_serviced',
            field=models.BooleanField(default=True, verbose_name='Site Serviced?'),
        ),
    ]
