# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-13 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0038_extendedinvoice_lineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSafetyReports',
            fields=[
            ],
            options={
                'verbose_name': 'Safety Report',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.extendedinvoice',),
        ),
        migrations.CreateModel(
            name='VendorWorkOrders',
            fields=[
            ],
            options={
                'verbose_name': 'Work Order',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.extendedinvoice',),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='reported_date',
            field=models.DateField(blank=True, default='2017-12-08', help_text='Date initial safety report batch was created', null=True),
        ),
    ]
