# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-13 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0039_auto_20180613_0416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorSafetyReports',
        ),
        migrations.DeleteModel(
            name='VendorWorkOrders',
        ),
        migrations.CreateModel(
            name='VendorSafetyReport',
            fields=[
            ],
            options={
                'verbose_name': 'Safety Report',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.extendedinvoice',),
        ),
        migrations.CreateModel(
            name='VendorWorkOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Work Order',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('invoices.extendedinvoice',),
        ),
    ]
