# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-28 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0039_auto_20180626_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='weather_ready',
            field=models.BooleanField(default=False),
        ),
    ]
