# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 09:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0040_invoice_weather_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='last_service_date',
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='verify_weather',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='verify_weather',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
