# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-13 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0040_auto_20180613_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='service_provided',
            field=models.BooleanField(default=True, verbose_name='Was service provided?'),
        ),
    ]
