# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0043_auto_20180629_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discrepancyreviewvendor',
            options={'verbose_name': 'Discrepancy Review'},
        ),
        migrations.AlterModelOptions(
            name='serviceforecastitemnwa',
            options={'verbose_name': 'Invoice'},
        ),
        migrations.AlterModelOptions(
            name='serviceforecastnwa',
            options={'verbose_name': 'Initial Spend Forecast'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('not_created', 'Safety Report - Initial'), ('safety_report', 'Closeout Report Generated'), ('preliminary_created', 'Preliminary Invoice - In Progress'), ('submitted', 'Invoice Submitted - In Review'), ('reviewed', 'Reviewed'), ('dispute', 'In Dispute'), ('finalized', 'Approved')], default='not_created', max_length=255, null=True),
        ),
    ]
