# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0044_auto_20180704_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyreport',
            name='inspection_date',
            field=models.DateField(blank=True, default='2017-12-09', help_text='Date of the safety check', null=True),
        ),
        migrations.AlterField(
            model_name='safetyvisit',
            name='inspection_date',
            field=models.DateField(blank=True, default='2017-12-09', help_text='Date of the safety check', null=True),
        ),
    ]
